pub static INDEX: &'static str = r#"<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>{{title}}</title>
		<meta name="description" content="Simple FileSharing Service">
		<meta name="author" content="Nyxiative">
	</head>
	<body>
		<form action="{{webroot}}/upload" method="post" enctype="multipart/form-data">
			<label for="file">{{label}}</label><br />
			<input type="file" name="file" id="file" /><br />
			<input type="checkbox" name="public" checked />
			<label for="public">Public File?</label><br />
			<span>Should the file be index, in the public file repository (Public repository not yet added)</span><br />
			<input type="checkbox" name="protected" />
			<label for="protected">Protected File?</label><br />
			<span>Should the file be protected with a password, this means that the file will require a ?password=PASSWORD to access (Password is autogenerated, Files are NOT encrypted)</span><br />
			<input type="checkbox" name="no_preview" />
			<label for="no_preview">Disable Preview?</label>
			<span>Should people be able to preview the file (View PDF/Image/Audio... in the browser), this doesn't affect non-previewable files anyway(Not yet implemented)</span><br /><br />
			<input type="submit" value="Submit" />
		</form>
	</body>
</html>"#;
pub static UPLOAD: &'static str = r#"<a href="{{webroot}}/{{code}}">{{url}}{{webroot}}/{{code}}<a/>"#;
pub static UPLOAD_PASSWORD: &'static str = r#"<a href="{{webroot}}/{{code}}?password={{password}}">{{url}}{{webroot}}/{{code}}?password={{password}}<a/>"#;
pub static UPLOAD_API: &'static str = r#"{{url}}{{webroot}}/{{code}}"#;
